<a href="https://colab.research.google.com/github/Bharat41/-data-science-lab-exp01/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Section 1: Array Creation & Properties

In [ ]:
import numpy as np

# Q1. Create a NumPy array from [10, 20, 30, 40, 50]. Display its shape, size, and data type.
arr1 = np.array([10, 20, 30, 40, 50])
print("Q1:")
print("Array:", arr1)
print("Shape:", arr1.shape)
print("Size:", arr1.size)
print("Data Type:", arr1.dtype)
print("-" * 40)

In [6]:
import numpy as np
# Q2. Create a 3 x 4 array containing numbers from 1 to 12.
arr2 = np.arange(1, 13).reshape(3, 4)
print("Q2:")
print("3x4 Array:\n", arr2)
print("-" * 40)

Q2:
3x4 Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
----------------------------------------


In [7]:
import numpy as np
# Q3. Create an array of zeros, an array of ones, and an identity matrix.
zeros_arr = np.zeros((2, 3))
ones_arr = np.ones((2, 3))
identity_matrix = np.eye(3)

print("Q3:")
print("Zeros (2x3):\n", zeros_arr)
print("Ones (2x3):\n", ones_arr)
print("Identity Matrix (3x3):\n", identity_matrix)
print("-" * 40)

Q3:
Zeros (2x3):
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones (2x3):
 [[1. 1. 1.]
 [1. 1. 1.]]
Identity Matrix (3x3):
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
----------------------------------------


In [8]:
import numpy as np
# Q4. Generate all even numbers between 10 and 50 using np.arange().
even_numbers = np.arange(10, 51, 2)
print("Q4:")
print("Even numbers from 10 to 50:", even_numbers)
print("-" * 40)

Q4:
Even numbers from 10 to 50: [10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]
----------------------------------------


In [9]:
import numpy as np
# Q5. Create an array of 10 equally spaced numbers between 0 and 1 using np.linspace().
linspace_arr = np.linspace(0, 1, 10)
print("Q5:")
print("10 equally spaced numbers between 0 and 1:\n", linspace_arr)

Q5:
10 equally spaced numbers between 0 and 1:
 [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


# Section 9: Statistical Operations

In [10]:
import numpy as np

# Q31. Given a 3 x 3 matrix, calculate its total sum, mean, variance, and standard deviation.
matrix_stat = np.array([[12, 15, 18], [22, 25, 28], [32, 35, 38]])
print("Q31:")
print("Matrix:\n", matrix_stat)
print("Total Sum:", np.sum(matrix_stat))
print("Mean:", np.mean(matrix_stat))
print("Variance:", np.var(matrix_stat))
print("Standard Deviation:", np.std(matrix_stat))
print("-" * 40)

Q31:
Matrix:
 [[12 15 18]
 [22 25 28]
 [32 35 38]]
Total Sum: 225
Mean: 25.0
Variance: 72.66666666666667
Standard Deviation: 8.524474568362947
----------------------------------------


In [11]:
import numpy as np

# Q32. Calculate row-wise and column-wise sums using axis.
matrix_stat = np.array([[12, 15, 18], [22, 25, 28], [32, 35, 38]])
row_sums = np.sum(matrix_stat, axis=1)
col_sums = np.sum(matrix_stat, axis=0)
print("Q32:")
print("Row-wise sums (axis=1):", row_sums)
print("Column-wise sums (axis=0):", col_sums)
print("-" * 40)

Q32:
Row-wise sums (axis=1): [ 45  75 105]
Column-wise sums (axis=0): [66 75 84]
----------------------------------------


In [12]:
import numpy as np

# Q33. Given the marks of 10 students, calculate mean, standard deviation, minimum, and maximum.
student_marks = np.array([55, 62, 45, 90, 81, 35, 76, 88, 42, 69])
print("Q33:")
print("Marks:", student_marks)
print("Mean:", np.mean(student_marks))
print("Standard Deviation:", np.std(student_marks))
print("Minimum:", np.min(student_marks))
print("Maximum:", np.max(student_marks))
print("-" * 40)

Q33:
Marks: [55 62 45 90 81 35 76 88 42 69]
Mean: 64.3
Standard Deviation: 18.655026132385878
Minimum: 35
Maximum: 90
----------------------------------------


In [13]:
import numpy as np

# Q34. Demonstrate the difference between any() and all() using a Boolean array.
bool_arr = np.array([True, False, True, True])
print("Q34:")
print("Boolean Array:", bool_arr)
print("Any element is True (any()):", np.any(bool_arr))
print("All elements are True (all()):", np.all(bool_arr))
print("-" * 40)

Q34:
Boolean Array: [ True False  True  True]
Any element is True (any()): True
All elements are True (all()): False
----------------------------------------


# Section 10: Sorting & Unique Values

In [14]:
import numpy as np

# Q35. Generate 10 random numbers and sort them.
np.random.seed(24)
rand_nums = np.random.randint(1, 100, 10)
print("Q35:")
print("Original random numbers:", rand_nums)
print("Sorted random numbers:", np.sort(rand_nums))
print("-" * 40)

Q35:
Original random numbers: [35  4 65 88 18 18  2 80  5 83]
Sorted random numbers: [ 2  4  5 18 18 35 65 80 83 88]
----------------------------------------


In [15]:
import numpy as np

# Q36. Given an array containing repeated values, find its unique elements.
repeated_vals = np.array([1, 2, 2, 3, 4, 4, 4, 5, 1, 6])
unique_vals = np.unique(repeated_vals)
print("Q36:")
print("Original Array:", repeated_vals)
print("Unique Elements:", unique_vals)
print("-" * 40)

Q36:
Original Array: [1 2 2 3 4 4 4 5 1 6]
Unique Elements: [1 2 3 4 5 6]
----------------------------------------


In [16]:
import numpy as np

# Q37. Given an array of student marks, find the unique marks.
marks_arr = np.array([45, 60, 55, 60, 45, 80, 90, 80])
unique_marks = np.unique(marks_arr)
print("Q37:")
print("Marks:", marks_arr)
print("Unique Marks:", unique_marks)
print("-" * 40)

Q37:
Marks: [45 60 55 60 45 80 90 80]
Unique Marks: [45 55 60 80 90]
----------------------------------------


In [17]:
import numpy as np

# Q38. Use np.in1d() to check whether selected values occur in an array.
full_arr = np.array([10, 20, 30, 40, 50])
check_vals = np.array([20, 35, 50])
presence_mask = np.in1d(check_vals, full_arr)
print("Q38:")
print("Full Array:", full_arr)
print("Checking Values:", check_vals)
print("Check Results (does value exist?):", presence_mask)
print("-" * 40)

Q38:
Full Array: [10 20 30 40 50]
Checking Values: [20 35 50]
Check Results (does value exist?): [ True False  True]
----------------------------------------


/tmp/ipykernel_788/461101918.py:6: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  presence_mask = np.in1d(check_vals, full_arr)


# Section 11: Integrated Lab Questions

In [18]:
import numpy as np

# Q39. Student Marks Analysis: Create a NumPy array containing marks of 10 students in 3 subjects.
# Calculate each student's total and average marks. Identify students whose average is >= 50 using np.where().
np.random.seed(5)
marks_matrix = np.random.randint(30, 100, size=(10, 3))
total_marks = np.sum(marks_matrix, axis=1)
average_marks = np.mean(marks_matrix, axis=1)
pass_students = np.where(average_marks >= 50)[0]

print("Q39:")
print("Marks (10 Students x 3 Subjects):\n", marks_matrix)
print("Total Marks:", total_marks)
print("Average Marks:", np.round(average_marks, 2))
print("Indices of students with Average >= 50:", pass_students)
print("-" * 40)

Q39:
Marks (10 Students x 3 Subjects):
 [[91 46 38]
 [92 57 60]
 [37 45 83]
 [57 74 95]
 [77 60 48]
 [39 71 92]
 [31 46 35]
 [88 30 34]
 [66 81 57]
 [61 32 98]]
Total Marks: [175 209 165 226 185 202 112 152 204 191]
Average Marks: [58.33 69.67 55.   75.33 61.67 67.33 37.33 50.67 68.   63.67]
Indices of students with Average >= 50: [0 1 2 3 4 5 7 8 9]
----------------------------------------


In [19]:
import numpy as np

# Q40. Matrix Analysis: Create a 4 x 4 matrix containing numbers 1-16.
# Find its transpose, row-wise sums, column-wise sums, mean, maximum, and minimum. Extract the central 2 x 2 matrix.
mat_4x4 = np.arange(1, 17).reshape(4, 4)
central_mat = mat_4x4[1:3, 1:3]

print("Q40:")
print("4x4 Matrix:\n", mat_4x4)
print("Transpose:\n", mat_4x4.T)
print("Row-wise Sums:", np.sum(mat_4x4, axis=1))
print("Column-wise Sums:", np.sum(mat_4x4, axis=0))
print("Overall Mean:", np.mean(mat_4x4))
print("Overall Max:", np.max(mat_4x4))
print("Overall Min:", np.min(mat_4x4))
print("Central 2x2 Matrix:\n", central_mat)
print("-" * 40)

Q40:
4x4 Matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Transpose:
 [[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]
Row-wise Sums: [10 26 42 58]
Column-wise Sums: [28 32 36 40]
Overall Mean: 8.5
Overall Max: 16
Overall Min: 1
Central 2x2 Matrix:
 [[ 6  7]
 [10 11]]
----------------------------------------


In [ ]:
import numpy as np

# Calculate statistics for the central 2x2 matrix from Q40
central_sum = np.sum(central_mat)
central_mean = np.mean(central_mat)
central_max = np.max(central_mat)
central_min = np.min(central_mat)
central_std = np.std(central_mat)

print("Statistics for the Central 2x2 Matrix:")
print("Central Matrix:\n", central_mat)
print("Sum:", central_sum)
print("Mean:", central_mean)
print("Max:", central_max)
print("Min:", central_min)
print("Standard Deviation:", np.round(central_std, 4))

In [48]:
import numpy as np

# Transpose the central 2x2 matrix from Q40
transposed_central = central_mat.T
mean_transposed_central = np.mean(transposed_central)

print("Transposed Central Matrix:\n", transposed_central)
print("Mean of Transposed Central Matrix:", mean_transposed_central)

Transposed Central Matrix:
 [[ 6 10]
 [ 7 11]]
Mean of Transposed Central Matrix: 8.5


In [20]:
import numpy as np

# Q41. Random Data Analysis: Generate 20 observations using np.random.randn().
# Calculate mean, standard deviation, minimum, maximum, and sorted values.
# Replace all negative observations with zero using np.where().
np.random.seed(8)
obs = np.random.randn(20)
sorted_obs = np.sort(obs)
positive_obs = np.where(obs < 0, 0, obs)

print("Q41:")
print("Generated Observations:\n", obs)
print("Mean:", np.mean(obs))
print("Standard Deviation:", np.std(obs))
print("Minimum:", np.min(obs))
print("Maximum:", np.max(obs))
print("Sorted Observations:\n", sorted_obs)
print("Negative Values Replaced with Zero:\n", positive_obs)
print("-" * 40)

Q41:
Generated Observations:
 [ 0.09120472  1.09128273 -1.94697031 -1.38634953 -2.29649157  2.4098343
  1.72783617  2.20455628  0.79482764  0.9764211  -1.18342715  1.91636361
 -1.1233268  -0.66403547 -0.37835857 -0.79161527  0.85954811 -0.230789
 -0.06566103 -0.20863623]
Mean: 0.08981068643586912
Standard Deviation: 1.3350628867371146
Minimum: -2.2964915742021637
Maximum: 2.4098343033415413
Sorted Observations:
 [-2.29649157 -1.94697031 -1.38634953 -1.18342715 -1.1233268  -0.79161527
 -0.66403547 -0.37835857 -0.230789   -0.20863623 -0.06566103  0.09120472
  0.79482764  0.85954811  0.9764211   1.09128273  1.72783617  1.91636361
  2.20455628  2.4098343 ]
Negative Values Replaced with Zero:
 [0.09120472 1.09128273 0.         0.         0.         2.4098343
 1.72783617 2.20455628 0.79482764 0.9764211  0.         1.91636361
 0.         0.         0.         0.         0.85954811 0.
 0.         0.        ]
----------------------------------------


In [21]:
import numpy as np

# Q42. Matrix Operations Challenge: Create two 3 x 3 matrices and perform:
# Element-wise addition, element-wise multiplication, matrix multiplication,
# transpose of the first matrix, and maximum/minimum of the resulting matrix.
np.random.seed(12)
M1 = np.random.randint(1, 10, size=(3, 3))
M2 = np.random.randint(1, 10, size=(3, 3))
matmul_res = np.dot(M1, M2)

print("Q42:")
print("Matrix M1:\n", M1)
print("Matrix M2:\n", M2)
print("Element-wise Addition:\n", M1 + M2)
print("Element-wise Multiplication:\n", M1 * M2)
print("Matrix Multiplication:\n", matmul_res)
print("Transpose of M1:\n", M1.T)
print("Max of resulting product matrix:", np.max(matmul_res))
print("Min of resulting product matrix:", np.min(matmul_res))
print("-" * 40)

Q42:
Matrix M1:
 [[7 2 3]
 [4 4 1]
 [7 2 5]]
Matrix M2:
 [[6 3 7]
 [1 6 9]
 [3 4 5]]
Element-wise Addition:
 [[13  5 10]
 [ 5 10 10]
 [10  6 10]]
Element-wise Multiplication:
 [[42  6 21]
 [ 4 24  9]
 [21  8 25]]
Matrix Multiplication:
 [[53 45 82]
 [31 40 69]
 [59 53 92]]
Transpose of M1:
 [[7 4 7]
 [2 4 2]
 [3 1 5]]
Max of resulting product matrix: 92
Min of resulting product matrix: 31
----------------------------------------


In [22]:
import numpy as np

# Q43. Array Manipulation Challenge: Create an array containing 1-24, reshape it into a 4 x 6 matrix,
# extract selected rows and columns, transpose it, calculate row/column statistics, and identify unique values.
arr_24 = np.arange(1, 25).reshape(4, 6)
extracted_part = arr_24[0:2, 1:4] # rows 0-1, cols 1-3
transposed_part = extracted_part.T

print("Q43:")
print("Reshaped 4x6 Matrix:\n", arr_24)
print("Extracted rows 0-1 and cols 1-3:\n", extracted_part)
print("Transposed Part:\n", transposed_part)
print("Row-wise sum of reshaped matrix:", np.sum(arr_24, axis=1))
print("Column-wise mean of reshaped matrix:", np.mean(arr_24, axis=0))
print("Unique Values in the matrix:", np.unique(arr_24))

Q43:
Reshaped 4x6 Matrix:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
Extracted rows 0-1 and cols 1-3:
 [[ 2  3  4]
 [ 8  9 10]]
Transposed Part:
 [[ 2  8]
 [ 3  9]
 [ 4 10]]
Row-wise sum of reshaped matrix: [ 21  57  93 129]
Column-wise mean of reshaped matrix: [10. 11. 12. 13. 14. 15.]
Unique Values in the matrix: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


# Section 6: Matrix Operations

In [23]:
import numpy as np

# Q21. Create two 3 x 3 matrices and perform element-wise addition and multiplication.
mat_A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
mat_B = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])
print("Q21:")
print("Element-wise Addition:\n", mat_A + mat_B)
print("Element-wise Multiplication:\n", mat_A * mat_B)
print("-" * 40)

Q21:
Element-wise Addition:
 [[10 10 10]
 [10 10 10]
 [10 10 10]]
Element-wise Multiplication:
 [[ 9 16 21]
 [24 25 24]
 [21 16  9]]
----------------------------------------


In [24]:
import numpy as np

# Q22. Calculate the matrix product of two compatible matrices using np.dot().
mat_A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
mat_B = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])
matrix_product = np.dot(mat_A, mat_B)
print("Q22:")
print("Matrix Product using np.dot():\n", matrix_product)
print("-" * 40)

Q22:
Matrix Product using np.dot():
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
----------------------------------------


In [25]:
import numpy as np

# Q23. Find the transpose of a matrix and calculate its dot product with the original matrix.
mat_A = np.array([[1, 2], [3, 4], [5, 6]])
mat_A_T = mat_A.T
dot_product_res = np.dot(mat_A_T, mat_A)
print("Q23:")
print("Original Matrix (3x2):\n", mat_A)
print("Transpose Matrix (2x3):\n", mat_A_T)
print("Dot product (A_T . A):\n", dot_product_res)
print("-" * 40)

Q23:
Original Matrix (3x2):
 [[1 2]
 [3 4]
 [5 6]]
Transpose Matrix (2x3):
 [[1 3 5]
 [2 4 6]]
Dot product (A_T . A):
 [[35 44]
 [44 56]]
----------------------------------------


# Section 7: Universal Functions

In [26]:
import numpy as np

# Q24. Calculate the square root of every element in an array using NumPy.
arr_val = np.array([4, 9, 16, 25])
print("Q24:")
print("Original:", arr_val)
print("Square root:", np.sqrt(arr_val))
print("-" * 40)

Q24:
Original: [ 4  9 16 25]
Square root: [2. 3. 4. 5.]
----------------------------------------


In [27]:
import numpy as np

# Q25. Calculate e^x for every element of an array.
arr_exp = np.array([0, 1, 2, 3])
print("Q25:")
print("Original:", arr_exp)
print("Exponential (e^x):", np.exp(arr_exp))
print("-" * 40)

Q25:
Original: [0 1 2 3]
Exponential (e^x): [ 1.          2.71828183  7.3890561  20.08553692]
----------------------------------------


In [28]:
import numpy as np

# Q26. Generate a random array and calculate its square root, exponential, and absolute values.
np.random.seed(42)
rand_arr = np.random.uniform(-5, 5, 5)
print("Q26:")
print("Random Array:", rand_arr)
print("Absolute Values:", np.abs(rand_arr))
print("Exponential:", np.exp(rand_arr))
# Using absolute value to avoid NaN in square root of negative numbers
print("Square Root of Abs values:", np.sqrt(np.abs(rand_arr)))
print("-" * 40)

Q26:
Random Array: [-1.25459881  4.50714306  2.31993942  0.98658484 -3.4398136 ]
Absolute Values: [1.25459881 4.50714306 2.31993942 0.98658484 3.4398136 ]
Exponential: [2.85190240e-01 9.06624314e+01 1.01750579e+01 2.68205916e+00
 3.20706629e-02]
Square Root of Abs values: [1.12008875 2.12300331 1.52313473 0.99326977 1.85467345]
----------------------------------------


In [29]:
import numpy as np

# Q27. Generate two random arrays and find their element-wise maximum.
np.random.seed(10)
rand_a = np.random.randint(1, 100, 5)
rand_b = np.random.randint(1, 100, 5)
print("Q27:")
print("Array A:", rand_a)
print("Array B:", rand_b)
print("Element-wise Maximum:", np.maximum(rand_a, rand_b))
print("-" * 40)

Q27:
Array A: [10 16 65 29 90]
Array B: [94 30  9 74  1]
Element-wise Maximum: [94 30 65 74 90]
----------------------------------------


# Section 8: np.where()

In [30]:
import numpy as np

# Q28. Given marks = np.array([35,72,48,90,55,28]), replace marks below 40 with 0 using np.where().
marks = np.array([35, 72, 48, 90, 55, 28])
updated_marks = np.where(marks < 40, 0, marks)
print("Q28:")
print("Original Marks:", marks)
print("After Replacing marks < 40 with 0:", updated_marks)
print("-" * 40)

Q28:
Original Marks: [35 72 48 90 55 28]
After Replacing marks < 40 with 0: [ 0 72 48 90 55  0]
----------------------------------------


In [31]:
import numpy as np

# Q29. Given an income array, classify observations as 'High' if income >= 50,000 and 'Low' otherwise.
income = np.array([32000, 55000, 48000, 120000, 49999, 50000])
classification = np.where(income >= 50000, 'High', 'Low')
print("Q29:")
print("Income:", income)
print("Classification:", classification)
print("-" * 40)

Q29:
Income: [ 32000  55000  48000 120000  49999  50000]
Classification: ['Low' 'High' 'Low' 'High' 'Low' 'High']
----------------------------------------


In [32]:
import numpy as np

# Q30. Replace all values greater than 30 in an array with 100 using np.where().
arr_30 = np.array([12, 45, 23, 89, 5, 31, 30])
modified_arr_30 = np.where(arr_30 > 30, 100, arr_30)
print("Q30:")
print("Original Array:", arr_30)
print("Modified Array (values > 30 replaced with 100):", modified_arr_30)

Q30:
Original Array: [12 45 23 89  5 31 30]
Modified Array (values > 30 replaced with 100): [ 12 100  23 100   5 100  30]


# Section 4: 2-D Array Indexing & Slicing

In [33]:
import numpy as np

# Q14. Create the matrix [[10,20,30],[40,50,60],[70,80,90]].
# Extract the second row, third column, and element 50.
matrix = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print("Q14:")
print("Matrix:\n", matrix)
print("Second Row:", matrix[1, :])
print("Third Column:", matrix[:, 2])
print("Element 50:", matrix[1, 1])
print("-" * 40)

Q14:
Matrix:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
Second Row: [40 50 60]
Third Column: [30 60 90]
Element 50: 50
----------------------------------------


In [34]:
import numpy as np

# Q15. From the matrix above, extract the sub-matrix [[20,30],[50,60]].
# (using the previously defined 'matrix')
matrix = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
sub_matrix = matrix[0:2, 1:3]
print("Q15:")
print("Sub-matrix:\n", sub_matrix)
print("-" * 40)

Q15:
Sub-matrix:
 [[20 30]
 [50 60]]
----------------------------------------


In [35]:
import numpy as np

# Q16. Create a 5 x 5 matrix containing 1-25 and extract:
# first row, last column, middle element, and top-left 3 x 3 matrix.
mat_5x5 = np.arange(1, 26).reshape(5, 5)
print("Q16:")
print("5x5 Matrix:\n", mat_5x5)
print("First Row:", mat_5x5[0, :])
print("Last Column:", mat_5x5[:, -1])
print("Middle Element:", mat_5x5[2, 2])
print("Top-Left 3x3:\n", mat_5x5[0:3, 0:3])
print("-" * 40)

Q16:
5x5 Matrix:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
First Row: [1 2 3 4 5]
Last Column: [ 5 10 15 20 25]
Middle Element: 13
Top-Left 3x3:
 [[ 1  2  3]
 [ 6  7  8]
 [11 12 13]]
----------------------------------------


# Section 5: Reshaping & Transpose

In [36]:
import numpy as np

# Q17. Create an array containing 1-12 and reshape it into a 3 x 4 matrix.
arr_1_12 = np.arange(1, 13)
reshaped_3x4 = arr_1_12.reshape(3, 4)
print("Q17:")
print("Reshaped 3x4 Matrix:\n", reshaped_3x4)
print("-" * 40)

Q17:
Reshaped 3x4 Matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
----------------------------------------


In [37]:
import numpy as np

# Q18. Reshape a 1-D array into a 2 x 5 matrix.
arr_1_10 = np.arange(10)
reshaped_2x5 = arr_1_10.reshape(2, 5)
print("Q18:")
print("Reshaped 2x5 Matrix:\n", reshaped_2x5)
print("-" * 40)

Q18:
Reshaped 2x5 Matrix:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
----------------------------------------


In [38]:
import numpy as np

# Q19. Convert a 3 x 4 matrix into a 4 x 3 matrix using transpose.
mat_3x4 = np.arange(1, 13).reshape(3, 4)
mat_4x3 = mat_3x4.T
print("Q19:")
print("Original 3x4:\n", mat_3x4)
print("Transposed 4x3:\n", mat_4x3)
print("-" * 40)

Q19:
Original 3x4:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Transposed 4x3:
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
----------------------------------------


In [39]:
import numpy as np

# Q20. Use transpose() and swapaxes() on a 3-D array.
arr_3d = np.arange(24).reshape(2, 3, 4)
print("Q20:")
print("Original 3D shape:", arr_3d.shape)
print("Transpose (axes permuted 1, 0, 2) shape:", np.transpose(arr_3d, (1, 0, 2)).shape)
print("Swapaxes (axis 0 and 1) shape:", np.swapaxes(arr_3d, 0, 1).shape)

Q20:
Original 3D shape: (2, 3, 4)
Transpose (axes permuted 1, 0, 2) shape: (3, 2, 4)
Swapaxes (axis 0 and 1) shape: (3, 2, 4)


# Section 2: Array Arithmetic

In [40]:
import numpy as np

# Q6. Given two NumPy arrays, perform element-wise addition, subtraction, multiplication, and division.
a = np.array([10, 20, 30, 40])
b = np.array([2, 4, 5, 8])

print("Q6:")
print("Array a:", a)
print("Array b:", b)
print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)
print("-" * 40)

Q6:
Array a: [10 20 30 40]
Array b: [2 4 5 8]
Addition: [12 24 35 48]
Subtraction: [ 8 16 25 32]
Multiplication: [ 20  80 150 320]
Division: [5. 5. 6. 5.]
----------------------------------------


In [41]:
import numpy as np

# Q7. Calculate the square and cube of every element in a NumPy array.
arr = np.array([1, 2, 3, 4, 5])
print("Q7:")
print("Original Array:", arr)
print("Square:", np.square(arr))
print("Cube:", np.power(arr, 3))
print("-" * 40)

Q7:
Original Array: [1 2 3 4 5]
Square: [ 1  4  9 16 25]
Cube: [  1   8  27  64 125]
----------------------------------------


In [42]:
import numpy as np

# Q8. Increase every element of an array by 15%.
arr_pct = np.array([100, 200, 300, 400])
increased_arr = arr_pct * 1.15
print("Q8:")
print("Original:", arr_pct)
print("Increased by 15%:", increased_arr)
print("-" * 40)

Q8:
Original: [100 200 300 400]
Increased by 15%: [115. 230. 345. 460.]
----------------------------------------


In [43]:
import numpy as np

# Q9. Given two arrays, find their element-wise maximum and minimum.
arr_x = np.array([5, 12, 18, 2])
arr_y = np.array([10, 8, 15, 20])
print("Q9:")
print("Array X:", arr_x)
print("Array Y:", arr_y)
print("Element-wise Max:", np.maximum(arr_x, arr_y))
print("Element-wise Min:", np.minimum(arr_x, arr_y))
print("-" * 40)

Q9:
Array X: [ 5 12 18  2]
Array Y: [10  8 15 20]
Element-wise Max: [10 12 18 20]
Element-wise Min: [ 5  8 15  2]
----------------------------------------


# Section 3: Indexing & Slicing

In [44]:
import numpy as np

# Q10. Create an array from 0 to 20 and extract:
# first five elements, last five elements, elements from index 5 to 15, and every second element.
arr_slice = np.arange(21)
print("Q10:")
print("Array:", arr_slice)
print("First five:", arr_slice[:5])
print("Last five:", arr_slice[-5:])
print("Index 5 to 15:", arr_slice[5:16])
print("Every second element:", arr_slice[::2])
print("-" * 40)

Q10:
Array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
First five: [0 1 2 3 4]
Last five: [16 17 18 19 20]
Index 5 to 15: [ 5  6  7  8  9 10 11 12 13 14 15]
Every second element: [ 0  2  4  6  8 10 12 14 16 18 20]
----------------------------------------


In [45]:
import numpy as np

# Q11. Replace the first five elements of an array with 100.
arr_replace = np.arange(10)
print("Q11:")
print("Before replacement:", arr_replace)
arr_replace[:5] = 100
print("After replacement:", arr_replace)
print("-" * 40)

Q11:
Before replacement: [0 1 2 3 4 5 6 7 8 9]
After replacement: [100 100 100 100 100   5   6   7   8   9]
----------------------------------------


In [46]:
import numpy as np

# Q12. Create an array and demonstrate the difference between a slice/view and a copy.
original = np.array([1, 2, 3, 4, 5])

# View (Slice)
view_arr = original[1:4]
view_arr[0] = 99

# Copy
copy_arr = original.copy()
copy_arr[1] = 500

print("Q12:")
print("Original (Note index 1 changed because of the view modification):", original)
print("View modified:", view_arr)
print("Copy modified (Original remains unaffected by this):", copy_arr)
print("-" * 40)

Q12:
Original (Note index 1 changed because of the view modification): [ 1 99  3  4  5]
View modified: [99  3  4]
Copy modified (Original remains unaffected by this): [  1 500   3   4   5]
----------------------------------------


In [47]:
import numpy as np

# Q13. Reverse a NumPy array using slicing.
arr_rev = np.array([1, 2, 3, 4, 5])
reversed_arr = arr_rev[::-1]
print("Q13:")
print("Original:", arr_rev)
print("Reversed:", reversed_arr)

Q13:
Original: [1 2 3 4 5]
Reversed: [5 4 3 2 1]
